folio-org/mgr-tenant-entitlements

src/main/java/org/folio/entitlement/integration/folio/ModuleInstallationGraph.java, src/test/java/org/folio/entitlement/utils/ModuleInstallationGraphTest.java
Fix nullpointer if empty Provides in MDs
wrap provides collection with nullpointer-safe static method
inter-team …
=> Fix nullpointer if empty Provides in MDs

src/main/java/org/folio/entitlement/service/EntitlementCrudService.java, src/main/java/org/folio/entitlement/service/stage/EntitlementDependencyValidator.java, src/test/java/org/folio/entitlement/service/stage/EntitlementDependencyValidatorTest.java
Query entitlement table to get a list of installed apps instead of entitlement flow when checking for dependent applications on installing the app
* add a method to find installed dependent applications to `EntitlementCrudService`
* use it in `EntitlementDependencyValidator` to validate application before it can be uninstalled 
Ideally, all …
=> Query entitlement table to get installed apps instead of entitlement flow to validate application before uninstalling

src/main/resources/changelog/changes/v1.0.0/add-application-name-version-to-dependency-table.xml
Define `NOT NULL` constraints separately from column specification
* update DB scripts
inter-team dependencies …
=> Define NOT NULL constraints separately from column specification

pom.xml
Upgrade Keycloak client to the latest - `v23.0.3`
- Upgrade Keycloak client to the latest - `v23.0.3` by upgrading dependencies:
- `folio-backend-testing`
- `folio-security`
environment. Communication is paramount if that is …
=> MGRENTITLE-11 Upgrade Keycloak client to v23.0.3

.github/CODEOWNERS, .gitignore, PERSONAL_DATA_DISCLOSURE.md, pom.xml
Maven deploy works not properly. It should be fixed.
- fix pom file
- add required files
inter-team dependencies …
=> FIX: maven deployment issue

Jenkinsfile, src/test/java/org/folio/entitlement/support/extensions/impl/PostgresContainerExtension.java
Fix build issues with insufficient resources by changing Jenkins build node to "bigmem" and using "alpine" version of postgres in test containers.
environment. Communication is paramount if that is to be achieved, especially …
=> Change Jenkins build node to "bigmem", use "alpine" version of postgres in test containers

pom.xml
Since we've released several libraries, it would be great to update dependency versions.
- update dependency versions
- add scm in pom.xml
- fix plugin dependency issue
=> Fix: update versions

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, src/main/resources/swagger.api/mgr-tenant-entitlements.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
=> FOLIO-3678 MGRENTITLE-10 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml, src/main/java/org/folio/entitlement/integration/kafka/CapabilitiesEventPublisher.java
Fixes module compilation with newest applications-poc-tools:1.2.0
Fixes logging for CapabilitiesEventPublisher
- Use newest applications-poc-tools:1.2.0
- Fix logging for CapabilitiesEventPublisher
environment. Communication …
=> Use applications-poc-tools:1.2.0

pom.xml
Raise applications-poc-tools to v1.3.0-SNAPSHOT
While it's helpful for …
=> MGRAPPS-8 Raise applications-poc-tools to v1.3.0-SNAPSHOT

src/main/java/org/folio/entitlement/integration/folio/ModuleInstallationGraph.java, src/test/java/org/folio/entitlement/integration/folio/ModuleInstallationGraphTest.java, src/test/java/org/folio/entitlement/utils/ModuleInstallationGraphTest.java
Prevent thread freeze during entitlement of applications with cyclic dependencies.
- Resolve all possible cyclic dependencies (intercepting cycling dependencies will be united to a single set)
- Add unit tests to verify algorithm
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the …
=> MGRENTITLE-34 Handle cyclic dependency during module installation

src/main/java/org/folio/entitlement/controller/EntitlementApplicationController.java, src/main/java/org/folio/entitlement/service/EntitlementApplicationService.java, src/test/java/org/folio/entitlement/it/EntitlementApplicationServiceIT.java, src/test/java/org/folio/entitlement/it/EntitlementApplicationServiceOkapiIT.java, src/test/java/org/folio/entitlement/service/EntitlementApplicationServiceTest.java, src/test/resources/wiremock/mgr-tenants/test/get-query-by-name-test2.json
Allow cross-tenant requests
Remove tenant header and path variable value equality validation
inter-team …
=> [MODROLESKC-26]: remove tenant header and path variable value equality validation

src/test/java/org/folio/entitlement/it/EntitlementApplicationServiceIT.java, src/test/java/org/folio/entitlement/it/EntitlementFlowIT.java, src/test/java/org/folio/entitlement/it/FolioEntitlementIT.java, src/test/java/org/folio/entitlement/support/KeycloakTestClientConfiguration.java, src/test/java/org/folio/entitlement/support/TestConstants.java, src/test/java/org/folio/entitlement/support/TestUtils.java, src/test/resources/application-it.yml
https://folio-org.atlassian.net/browse/APPPOCTOOL-10
Braking changes were added in application-poc-tools. Keycloak-related tests should be updated.
- fix tests
environment. Communication is paramount if that is to be …
=> APPPOCTOOL-10: update Keycloak-related tests

src/main/java/org/folio/entitlement/integration/keycloak/KeycloakAuthResourceCleaner.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakAuthResourceCreator.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakService.java, src/test/java/org/folio/entitlement/integration/keycloak/KeycloakAuthResourceCleanerTest.java, src/test/java/org/folio/entitlement/integration/keycloak/KeycloakServiceTest.java
Provides an option to update Keycloak authorization resources for upgrade operation.
- Keycloak service is extended with `updateAuthResources` method
- Unit tests are added for KeycloakService
- Integration tests will be added when upgrade flow will be implemented
Ideally, all the PRs involved in breaking changes would be merged on the same …
=> MGRENTITLE-19 Implement upgrade operation for Keycloak service

src/test/java/org/folio/entitlement/it/EntitlementRoutesIT.java, src/test/java/org/folio/entitlement/it/OkapiEntitlementIT.java
Include timer interface endpoint(s) into account in integration test asserts
US: [EUREKA-66](https://folio-org.atlassian.net/browse/EUREKA-66)
environment. Communication is paramount if that is to be achieved, especially as …
=> EUREKA-66 Include timer interface endpoint into account in integration test asserts

README.md, src/main/resources/application.yml
Add support TLS certificates issued by trusted certificate authorities for Keycloak client
Depends on PR: https://github.com/folio-org/applications-poc-tools/pull/93
environment. Communication is paramount if that is to be …
=> MGRENTITLE-54: Keycloak client: support TLS certificates issued by trusted certificate authorities

Jenkinsfile
Automatic Docker Image build
While it's helpful for reviewers to help identify …
=> .RANCHER-1502 mgr-tenant-entitlements

src/main/java/org/folio/entitlement/configuration/FlowEngineConfiguration.java
Replace fork-join pool with fixed thread pool to resolve issues with invalid resource consumption and frozen entitlement stages
- Replace FJP with fixed thread pool
environment. Communication is paramount if that is to be …
=> Replace Fork-Join pool with fixed thread pool

pom.xml
=> Release 1.2.2

src/test/java/org/folio/entitlement/it/EntitlementRoutesIT.java, src/test/java/org/folio/entitlement/support/extensions/impl/KongGatewayExtension.java
Upgrade kong version to 3.7.1
While it's helpful for reviewers to help …
=> KONG-10: upgrade kong version to 3.7.1

README.md, src/main/resources/swagger.api/mgr-tenant-entitlements.yaml
Improves documentation for entitlement flags
While it's helpful for reviewers …
=> MGRENTITLE-38 Improve documentation for entitlement query parameters

src/main/java/org/folio/entitlement/domain/model/ModuleDescriptorHolder.java, src/main/java/org/folio/entitlement/integration/folio/stage/FolioModuleEventPublisher.java, src/main/java/org/folio/entitlement/integration/folio/stage/FolioModuleUpdater.java, src/main/java/org/folio/entitlement/integration/kafka/AbstractEventPublisher.java, src/main/java/org/folio/entitlement/integration/kafka/AbstractModuleEventPublisher.java, src/main/java/org/folio/entitlement/integration/kafka/CapabilitiesEventPublisher.java, src/main/java/org/folio/entitlement/integration/kafka/CapabilitiesModuleEventPublisher.java, src/main/java/org/folio/entitlement/integration/kafka/model/CapabilityEventPayload.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakModuleResourceUpdater.java, src/main/java/org/folio/entitlement/integration/kong/KongModuleRouteUpdater.java, src/main/java/org/folio/entitlement/utils/EntitlementServiceUtils.java, src/test/java/org/folio/entitlement/integration/kafka/CapabilitiesEventPublisherTest.java, src/test/java/org/folio/entitlement/integration/kafka/CapabilitiesModuleEventPublisherTest.java, src/test/java/org/folio/entitlement/support/UpgradeTestValues.java, src/test/java/org/folio/entitlement/utils/EntitlementServiceUtilsTest.java, src/test/resources/json/events/capabilities/unchanged-module-event.json, src/test/resources/json/events/folio-app6/folio-module1/capability-application-id-update.json, src/test/resources/json/events/folio-app6/ui-module1/capability-application-id-update.json
Provides a event-marker to perform application version upgrades for non-changed module during upgrade operation
- Add an abstract to generate event-markers to perform an upgrade of the application version in affected modules
- Extend unit and integration test coverage
- 
Ideally, all the PRs involved in breaking changes would be merged on …
=> MODROLESKC-200 Implement application version upgrades for capability events

src/test/java/org/folio/entitlement/it/OkapiEntitlementIT.java, src/test/java/org/folio/entitlement/support/UpgradeTestValues.java, src/test/resources/json/events/okapi-it/okapi-module1/scheduled-job-event.json, src/test/resources/wiremock/mgr-applications/okapi-app/get-by-ids-query-full.json, src/test/resources/wiremock/mgr-applications/okapi-app15/get-by-ids-query-full.json
application-poc-tools was updated in scope of https://folio-org.atlassian.net/browse/APPPOCTOOL-25. Tests should be adjusted.
- adjust tests
environment. Communication is paramount if that is to be achieved, especially as …
=> APPPOCTOOL-25: adjust test after resource creation filter updated

Jenkinsfile
Enable docker build in Jenkinsfile.
=> Enable docker build in Jenkinsfile.

NEWS.md, pom.xml
=> Release 1.2.4

pom.xml, src/main/java/org/folio/entitlement/integration/am/AppManagerClientConfiguration.java, src/main/java/org/folio/entitlement/integration/folio/configuration/FolioConfiguration.java, src/main/java/org/folio/entitlement/integration/tm/TenantManagerClientConfiguration.java, src/test/java/org/folio/entitlement/it/DisableHostnameVerificationConfig.java
Bump up applications-poc-tools dependencies to 1.5.6 to support Hostname Verification for TLS connections
=> Bump up applications-poc-tools dependencies to 1.5.6

pom.xml
Increases keycloak-admin-client to v25.0.6
- Increases keycloak-admin-client to v25.0.6
- Use the latest snapshot versions of `applications-poc-tools` library components
environment. Communication is paramount if that is to …
=> KEYCLOAK-24 Increase keycloak-admin-client to v25.0.6

README.md, src/main/java/org/folio/entitlement/service/validator/InterfaceIntegrityValidator.java, src/main/java/org/folio/entitlement/service/validator/configuration/InterfaceIntegrityValidatorProperties.java, src/main/resources/application.yml, src/test/java/org/folio/entitlement/service/validator/InterfaceIntegrityValidatorTest.java, src/test/resources/application-it.yml
Add properties to be able to disable interface integrity validation for local envs.
inter-team dependencies …
=> Additional properties to configure validators

src/main/java/org/folio/entitlement/integration/kafka/CapabilitiesModuleEventPublisher.java, src/test/resources/json/events/capabilities/desc-with-unmatched-perms-event.json, src/test/resources/json/events/folio-app6/folio-module2/capability-update.json, src/test/resources/json/events/okapi-it/okapi-module-capability-event-2.json
While it's helpful for reviewers to help identify potential problems, ensuring …
=> MODROLESKC-233: Revert the changes that were previously made.

src/main/java/org/folio/entitlement/integration/kafka/KafkaEventUtils.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakService.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakUtils.java, src/test/java/org/folio/entitlement/integration/kafka/PermissionMappingLoaderTest.java, src/test/java/org/folio/entitlement/integration/keycloak/KeycloakUtilsTest.java
…not exist in the mod-pubsub module but are still required to be created in the keycloak
inter-team dependencies …
=> MODROLESKC-233: added logic to create resources for endpoints that do not exist in the mod-pub-sub module but are still required

src/main/resources/permissionmappings/mapping.json, src/test/java/org/folio/entitlement/integration/kafka/PermissionMappingLoaderTest.java, src/test/java/org/folio/entitlement/integration/keycloak/KeycloakUtilsTest.java
The proposed changes involve adding additional endpoints with new permissions to the mod-circulation module, used by system user of mod-pubsub module
[MGRENTITLE-89](https://folio-org.atlassian.net/browse/MGRENTITLE-89) …
=> MGRENTITLE-89: Added the missing mapping for the circulation module.

README.md, pom.xml, src/main/java/org/folio/entitlement/configuration/cache/AccessTokenExpiry.java, src/main/java/org/folio/entitlement/configuration/cache/CacheConfiguration.java, src/main/java/org/folio/entitlement/integration/keycloak/KeycloakCacheableService.java, src/main/java/org/folio/entitlement/integration/keycloak/configuration/properties/KeycloakConfigurationProperties.java, src/main/java/org/folio/entitlement/service/EntitlementApplicationService.java, src/main/resources/application.yml, src/test/java/org/folio/entitlement/it/EntitlementApplicationServiceTokenCacheIT.java, src/test/java/org/folio/entitlement/service/EntitlementApplicationServiceTest.java
https://folio-org.atlassian.net/browse/EUREKA-605
Introduced cache for Keycloak auth token.
=> EUREKA-605: introduced cache for Keycloak auth token

Dockerfile, Jenkinsfile, docker/Dockerfile.fips, pom.xml
https://folio-org.atlassian.net/browse/MGRENTITLE-102
Upgrade Java to v21 …
=> MGRENTITLE-102: Upgrade Java to v21.

src/main/resources/permissionmappings/mapping.json, src/test/java/org/folio/entitlement/integration/kafka/PermissionMappingLoaderTest.java, src/test/java/org/folio/entitlement/integration/keycloak/KeycloakUtilsTest.java
Add permission mappings for mod-patron-blocks pubsub event handlers.
Resolves [MGRENTITLE-107](https://folio-org.atlassian.net/browse/MGRENTITLE-107).
environment. Communication is paramount if that is to be achieved, …
=> MGRENTITLE-107: Add permission mappings for mod-patron-blocks

src/main/java/org/folio/entitlement/configuration/ReinstallConfiguration.java, src/main/java/org/folio/entitlement/controller/ReinstallController.java, src/main/java/org/folio/entitlement/integration/am/model/ModuleDiscovery.java, src/main/java/org/folio/entitlement/integration/folio/FolioModuleService.java, src/main/java/org/folio/entitlement/integration/folio/model/ModuleRequest.java, src/main/java/org/folio/entitlement/service/ReinstallService.java, src/main/java/org/folio/entitlement/utils/ParallelUtil.java, src/main/resources/descriptors/ModuleDescriptor.json, src/main/resources/swagger.api/mgr-tenant-entitlements.yaml, src/main/resources/swagger.api/schemas/appReinstallRequestBody.json, src/main/resources/swagger.api/schemas/moduleReinstallRequestBody.json, src/main/resources/swagger.api/schemas/reinstallResult.json, src/test/java/org/folio/entitlement/it/KongRegistrationIT.java, src/test/java/org/folio/entitlement/service/ReinstallServiceTest.java, src/test/java/org/folio/entitlement/utils/ParallelUtilTest.java
https://folio-org.atlassian.net/browse/MGRENTITLE-103
Feature-parity with OKAPI - have a "reinstall" endpoints that allow to call again _tenant endpoints of modules, with options to specify tenant parameters.
environment. …
=> MGRENTITLE-103: Implementation of reinstall functionality.

NEWS.md, pom.xml
Release 3.1.0
https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/522780695/Eureka+module+s+release+procedure
---
=> Tmp release 3.1.0

NEWS.md, pom.xml, src/main/java/org/folio/entitlement/domain/entity/ApplicationDependencyEntity.java, src/main/java/org/folio/entitlement/mapper/ApplicationDependencyMapper.java, src/main/resources/changelog/changelog-3.0.0.xml, src/main/resources/changelog/changes.v3.0.0/add-optional-filed-to-dependency-table.xml, src/main/resources/descriptors/ModuleDescriptor.json, src/test/java/org/folio/entitlement/it/KongRegistrationIT.java, src/test/java/org/folio/entitlement/support/TestValues.java
[MGRAPPS-57](https://folio-org.atlassian.net/browse/MGRAPPS-57)
Introduce the notion of optional dependencies at the application level
- Updated Dependency schema with a new field "optional"
---
=> MGRAPPS-57: Introduce optional application dependencies

src/main/java/org/folio/entitlement/integration/keycloak/configuration/KeycloakConfiguration.java
Update the code to reflect the changes done in application-poc-tools in this PR: https://github.com/folio-org/applications-poc-tools/pull/218
US: [FSSP-1](https://folio-org.atlassian.net/browse/FSSP-1)
* Replace `NotFoundException` with `SecretNotFoundException`
=> FSSP-1 Adopt to changes in secure store
